# Generated by Django 3.2.9 on 2021-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridehost',
            name='available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ridehost',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
