# Generated by Django 3.2.9 on 2021-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20211128_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepool',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
