# Generated by Django 3.2.9 on 2021-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_ridehost_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehost',
            name='destination',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ridehost',
            name='start_point',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
