# Generated by Django 3.2.9 on 2021-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ridepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridehost',
            name='Status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('EXPIRED', 'EXPIRED')], default='EXPIRED', max_length=500),
        ),
    ]
