# Generated by Django 3.2.9 on 2021-11-27 16:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehost',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='user.profile.contact', max_length=128, region=None),
        ),
    ]
