# Generated by Django 3.2.9 on 2021-11-29 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ridepool_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehost',
            name='available',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridehost',
            name='seats',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridehost',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
