# Generated by Django 3.2.9 on 2021-11-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ridehost_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridehost',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='ridepool',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED')], default='CANCELLED', max_length=500),
        ),
    ]
