# Generated by Django 3.2.9 on 2021-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20211129_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehost',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
